# Generated by Django 4.0.4 on 2022-05-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='length_a',
            field=models.FloatField(default=-0.1, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='length_b',
            field=models.FloatField(default=-0.1, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='length_c',
            field=models.FloatField(default=-0.1, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='shape',
            field=models.CharField(choices=[('triangle', 'triangle'), ('rectangle', 'rectangle'), ('square', 'square'), ('diamond', 'diamond')], default='triangle', max_length=20),
        ),
    ]
