# Generated by Django 4.0.4 on 2022-05-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_price_remove_product_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='length_a',
            new_name='a',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='length_b',
            new_name='b',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='length_c',
            new_name='c',
        ),
    ]
